name: Pre-build Devcontainers

on:
  workflow_dispatch:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pre-build Azure Functions Python
      uses: devcontainers/ci@v0.3
      with:
        configFile: ./src/func-python/.devcontainer/devcontainer.json
        imageName: ghcr.io/jlaundry/devcontainers/func-python
        cacheFrom: ghcr.io/jlaundry/devcontainers/func-python
        push: always